### PR TITLE
Update typescript dependency

### LINKED ISSUE #59: Unable to install other modules after installing this
Cannot install modules after install this package,
Have to uninstall first

```
error An unexpected error occurred: "could not find a copy of typescript to link in ...\\node_modules\\rxjs-tslint\\node_modules".
```

Typescript: 3.1.6
Rxjs-Tslint: 0.1.6

### PR DESCRIPTION
**Pull request by jdforsythe**
Updates the typescript dependency definition to allow versions greater than v3 to fix `yarn install` issues for those using this module with Angular v7.

Fixes #59

### CODE REVIEW

**Comment by jdforsythe** [comment]
```sh
> rimraf dist && tsc && mocha -R nyan dist/test --recursive

 14  -_-_-_-_-_-_-_-_,------,
 0   -_-_-_-_-_-_-_-_|   /\_/\
 0   -_-_-_-_-_-_-_-^|__( ^ .^)
     -_-_-_-_-_-_-_-  ""  ""

  14 passing (43ms)
```

**Comment by jrwpatterson** [comment]
any idea when this will happen?

**Comment by guilhermehtk** [comment]
up!

**Comment by NicholasMaestrello** [comment]
up

**Comment by JucieltonSantos** [comment]
up

**Comment by RodrigoKobayashi** [comment]
up

**Comment by diegodsgarcia** [comment]
up!

**Comment by mgechev** [comment]
Released under 0.1.7.

**Comment by tstackhouse** [comment]
Still seems broken here... TS 3.1.6, yarn 1.13.0, rxjs-tslint 0.1.7

**Comment by tstackhouse** [comment]
This is still broken...

**Pull request merged**
